# Generated by Django 4.2.5 on 2023-09-19 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheese', '0002_rename_type_cheese_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cheese',
            old_name='details',
            new_name='type',
        ),
    ]
